name: deploy-ghost-azure
concurrency: ghost-azure

on: 
  push:
    branches: 
      - main

env:
  AZURE_DEV_RESOURCEGROUP_NAME: j-ghost-dev-rg-01
  AZURE_PROD_RESOURCEGROUP_NAME: j-ghost-prod-rg-01
  APP_NAME_PREFIX: ghost
  SLOT_ENABLED: 'Yes'
  GHOST_CONTAINER: ghost:4.29.0-alpine
  AZURE_FUNCTIONAPP_NAME: ghost-fa-dev-yx2khfxzfxlrq    # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'function'      # set this to the path to your web app project, defaults to the repository root

jobs:
  # Lint the Bicep file.
  lint: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  # Validate the dev/test template
  validate: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
    - uses: azure/arm-deploy@v1
      name: Run preflight validation
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_DEV_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        parameters: environmentName=Development
                    applicationNamePrefix=${{ env.APP_NAME_PREFIX }}
                    webSlotEnabled=${{ env.SLOT_ENABLED }}
                    databasePassword=${{ secrets.DATABASEPASSWORD }}
                    ghostContainerName=${{ env.GHOST_CONTAINER }}
        deploymentMode: Validate

  # Run the what-if of the dev/test template
  preview:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
    - uses: Azure/cli@v1
      name: Run what-if
      with:
        inlineScript: |
            az deployment group what-if \
              --resource-group ${{ env.AZURE_DEV_RESOURCEGROUP_NAME }} \
              --template-file main.bicep \
              --parameters environmentName=Development \
                           applicationNamePrefix=${{ env.APP_NAME_PREFIX }} \
                           webSlotEnabled=${{ env.SLOT_ENABLED }} \
                           databasePassword=${{ secrets.DATABASEPASSWORD }} \
                           ghostContainerName=${{ env.GHOST_CONTAINER }}

  # Deploy the dev/test template
  deploy:
    runs-on: ubuntu-latest
    needs: preview
    outputs:
      endpointHostName: ${{ steps.deploy.outputs.endpointHostName }}
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
    - uses: azure/arm-deploy@v1
      id: deploy
      name: Deploy solution
      with:
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_DEV_RESOURCEGROUP_NAME }}
        template: ./main.bicep
        parameters: environmentName=Development
                    applicationNamePrefix=${{ env.APP_NAME_PREFIX }}
                    webSlotEnabled=${{ env.SLOT_ENABLED }}
                    databasePassword=${{ secrets.DATABASEPASSWORD }}
                    ghostContainerName=${{ env.GHOST_CONTAINER }}
    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

  # Run the dev/test smoke test
  smoke-test:
    runs-on: ubuntu-latest
    needs: deploy
    steps: 
    - uses: actions/checkout@v2
    - run: |
        $container = New-PesterContainer `
          -Path 'tests/Website.Tests.ps1' `
          -Data @{ HostName = '${{needs.deploy.outputs.endpointHostName}}' }
        Invoke-Pester `
          -Container $container `
          -CI
      name: Run smoke tests
      shell: pwsh
